### ISSUE TITLE
No output message

### ISSUE THREAD

**Issue by bartbutenaers** [DeanCording/node-red-contrib-ecolect#1]
Hey Dean,

Great contribution. Really makes my flow much more interactive.

Yesterday I suddenly noticed that my ecolect node stopped sending output messages.  After a while I found that _**I used in the phrases section a non-existing item**_.

For example, if you mispelled room as 'roommmm':
![image](https://user-images.githubusercontent.com/14224149/34745362-8cfa0ad6-f590-11e7-8f7d-5c307fe0101f.png)

Then no output message is generated, which is rather confusing...

Based on this config data:
![image](https://user-images.githubusercontent.com/14224149/34745532-252bc362-f591-11e7-8671-c0fb1eb44af9.png)

I assume you can check (whether the phrases contain an non-existing item) in two different ways:
- **.js file** : show a self-explaining error in the node status text
- **.html file** : extend the validation function (on the phrases), but then I think you only get an error.  But then he doesn't now what is wrong.

Would be nice if you could add some kind of validation.

Thanks !!!
Bart

**Comment by DeanCording** [comment]
Thanks Bart,

The node does output an error message on the Node Red console but nothing in the UI.  I will make a change so that the error shows up on the UI.

Dean

**Comment by DeanCording** [comment]
Improved the error handling so that it drops phrases that have problems, reports the error, and tags the node with the error message.

**Comment by bartbutenaers** [comment]
Hey Colin,

Now it is indeed clear to me what I have done wrong, bot in the node status and the console:

![image](https://user-images.githubusercontent.com/14224149/34789734-b2eee1f8-f63f-11e7-80e3-1ac56fff9523.png)

Keep up the good work !!
Bart

**Comment by bartbutenaers** [comment]
Damn...
Thanks Dean ;-)
