### ISSUE TITLE
Unable to enter phrases in ecolect and settings are not stored

### ISSUE THREAD

**Issue by aleonnet** [DeanCording/node-red-contrib-ecolect#3]
Hi @DeanCording !
First part of making google actions node work is done.
When it comes to ecolect the phrases cannot be inserted and the settings are not being stored by the node.
I tried to use the following flow and after importing it, only the topic is visible.

[{"id":"c9e9e9a0.faa628","type":"ecolect","z":"30254762.66c5f8","name":"","topics":[{"name":"gardenlight","phrases":"turn {state} the {room} {item} at {when}\nturn {item} {state} in {room} at {when}\nturn {state} {room} {item}\nturn {room} {item} {state}","values":[{"name":"room","type":"enumeration","enumerations":["kitchen","bedroom","bathroom"]},{"name":"item","type":"enumeration","enumerations":["light","fan","radio"]},{"name":"state","type":"boolean","enumerations":[]},{"name":"when","type":"date-time","enumerations":[]}]}],"outputs":2,"x":240,"y":360,"wires":[["9933520b.09721"],["9933520b.09721"]]},{"id":"9933520b.09721","type":"debug","z":"30254762.66c5f8","name":"","active":true,"console":"false","complete":"true","x":385,"y":361,"wires":[]},{"id":"ff746222.bd305","type":"inject","z":"30254762.66c5f8","name":"","topic":"","payload":"turn on the kitchen light at 9pm","payloadType":"str","repeat":"","crontab":"","once":false,"x":83,"y":360,"wires":[["c9e9e9a0.faa628"]]}]

I'm running my flow as root. I don't know if this has anythinh to do with this.

![screen shot 2018-02-17 at 3 45 49 pm](https://user-images.githubusercontent.com/20618327/36343921-df24e8c6-13f9-11e8-89ec-4f25c77f787a.png)

**Comment by DeanCording** [comment]
I've imported that flow and it works ok for me.  You may need to upgrade your ecolect nodefrom NPM as that screen dump doesn't look right due to bits missing.  The current version is 1.0.4

![image](https://user-images.githubusercontent.com/251170/36346113-b86a971e-1483-11e8-9dff-37d7510efacd.png)

**Comment by aleonnet** [comment]
Thanks Dean, but I'm using your latest version 1.0.4 installed from NPM.

I'm using Node-RED version: v0.16.2, Node.js  version: v6.13.0, Linux 4.9.35-v7+ arm LE all in RPI3.

**Comment by DeanCording** [comment]
> Node-RED version: v0.16.2, Node.js version: v6.13.0,

That could be an issue as v0.16.2 is quite old as the latest version is v0.18.3.   Node v6.13.0 is quite old as well as the latest is v8.9.4

**Comment by aleonnet** [comment]
It's also strange that even when uninstalled, the node isn't erased from palette. I'll upgrade Node-Red and NodeJS to the most let you know

**Comment by aleonnet** [comment]
Upgrading Node-Red to 0.18.3 did the trick. Thank you Dean.
