### ISSUE TITLE
missing module 'ecolect/values/index' (line:21)

### ISSUE THREAD

**Issue by Stamchat** [DeanCording/node-red-contrib-ecolect#5]
Hello, I have been trying to install ecolect node in Debian , ubuntu, raspbian  (latest versions in both operating system and nodered) and in all systems node-red halts after installation and deployment with the error 
23 Mar 13:50:13 - [warn] [node-red-contrib-ecolect/ecolect] Error: Cannot find module 'ecolect/values/index' (line:21)
Does anyone knows a solution to the problem?
Thanks in advance,
Stam

**Comment by MagnusDot** [comment]
Problem solved here : [LINK](https://github.com/MagnusDot/node-red-contrib-ecolect)
