### ISSUE TITLE
Nedds updating.

### ISSUE THREAD

**Issue by Stamchat** [DeanCording/node-red-contrib-ecolect#6]
Hello,
 I tred to use it but since there is a new version of ecolect 6.0, and nodered node (node-red-contrib-ecolect) is designed for a previous one,  the system halts when I try to use it.  It reports some missing files and when I manually copy them from previous version zip it reports some other missing etc and this behaviour never ends. 

23 Mar 13:50:13 - [warn] [node-red-contrib-ecolect/ecolect] Error: Cannot find module 'ecolect/values/index' (line:21)
Do you know a solution to the problem?
Thanks in advance,

Stam

**Comment by ghost** [comment]
Uninstall ecolect 6, and install the 0.5.2 version of ecolect specifically.
```
> npm uninstall ecolect
> npm install ecolect@0.5.2
```

**Comment by Stamchat** [comment]
Thanks a lot!

**Comment by ghost** [comment]
Hmm, while this stops the error messages when starting node-red, the ecolect node seems to lose its settings each time you change it and close the dialog, so don't think it fixes the issue, sorry!

**Comment by MagnusDot** [comment]
Problem solved here : [LINK](https://github.com/MagnusDot/node-red-contrib-ecolect)
