### ISSUE TITLE
"TypeError: ecolect.intents is not a function"

### ISSUE THREAD

**Issue by soloam** [DeanCording/node-red-contrib-ecolect#7]
Hello, I'm getting this error on Nodered "TypeError: ecolect.intents is not a function"

Nodered 0.20.6
Node 8.11.3
npm 6.3.0

**Comment by MagnusDot** [comment]
Problem solved here : [LINK]( https://github.com/MagnusDot/node-red-contrib-ecolect)

**Comment by soloam** [comment]
lets hope that @DeanCording accepts the merge.

How can I test your version? I normaly install the nodes from the GUI

**Comment by MagnusDot** [comment]
you can test it by intall it manually, for the GUI install you must wait  @DeanCording for accept the merge

**Comment by MagnusDot** [comment]
If he did not i will keep my fork in update and do a maintained project
